// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BlazmExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "BlazmExtension.a0f59921-9553-46c5-b0cf-4c4921326541";
        public const string Name = "BlazmExtension";
        public const string Description = @"Extension that helps you with common Blazor tasks like creating a Isolated CSS or JavaScript from a context menu item";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "EngstromJimmy";
        public const string Tags = "";
    }
}
