// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BlazmExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string BlazmExtensionString = "e12b1962-2ac4-416a-af19-2c6b8731922d";
        public static Guid BlazmExtension = new Guid(BlazmExtensionString);

        public const string RazorContextGuidString = "ba1aa6e4-68f5-4a4f-97c0-cbf91710430e";
        public static Guid RazorContextGuid = new Guid(RazorContextGuidString);

        public const string RazorCsContextGuidString = "8f08cd3a-1f0b-4114-8a32-b148e8505468";
        public static Guid RazorCsContextGuid = new Guid(RazorCsContextGuidString);

        public const string CssIconsString = "7d860ae9-adfa-4fda-b13b-083a6dd309b1";
        public static Guid CssIcons = new Guid(CssIconsString);

        public const string JsIconsString = "7d860ae9-adfa-4fda-b13b-083a6dd309b0";
        public static Guid JsIcons = new Guid(JsIconsString);

        public const string RazorIconsString = "7d860ae9-adfa-4fda-b13b-083a6dd309b2";
        public static Guid RazorIcons = new Guid(RazorIconsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int RazorFileMenu = 0x0002;
        public const int CreateIsolatedCss = 0x0100;
        public const int CreateIsolatedJavaScript = 0x0200;
        public const int MoveNamespace = 0x0300;
        public const int MoveCodebehind = 0x0400;
        public const int ExtractToComponent = 0x0500;
        public const int cssIcon = 0x0001;
        public const int jsIcon = 0x0001;
        public const int razorIcon = 0x0001;
    }
}